### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by At0micA55** [WolfKnight98/wk_wars2x#10]
**Describe the bug**
When the server start and players start to log in the server everyone see the radar and can't get rid of it whatever the key pressed... Tried all the keys and mouse click too

**To Reproduce**
Install the resource, start the server and login

**Expected behaviour**
That the radar only show when wanted (F5 pressed and in a police car ONLY)

**Screenshots**
None right now

**Desktop (please complete the following information):**
 - FiveM version: 3240
 - FiveM server version : unknown ?
 - Radar version : 1.2.4

**Additional context**
All Files are default except the : `CONFIG.allow_quick_start_video = false`

**Comment by WolfKnight98** [comment]
How long has this been happening? Also, it would help to know what server artifacts version you're using.

**Comment by At0micA55** [comment]
I just installed this ressources and since it's installed it's doing this :/ I got the ressources from here and like i said the only thing i changed in it was the `CONFIG.allow_quick_start_video = false`

Also server version is : `FXServer-master v1.0.0.3148 linux`

**Comment by WolfKnight98** [comment]
Hmm, ensure all files have been installed properly. I've had issues like this before and the culprit was that some of the files didn't transfer properly, mainly the jQuery JS file.
