### ISSUE TITLE
Toggle Radar and Plate Reader Display Error

### ISSUE THREAD

**Issue by WhackySnax** [WolfKnight98/wk_wars2x#11]
Hello, I have come across an issue with the toggle display and plate reader functions on the remote. When I pull up the remote and click on the toggle display they fail to display which forces me to close the game and relaunch. I was wondering if you know of any solutions to the problem. I have attempted to use the /reset_radar command along with making sure all of my aspect ratios and such else were set up properly. This problem is only happening to me as well and not and other users.

Thank you.

**Comment by WolfKnight98** [comment]
This is an issue that has been happening for a while, I've got absolutely no idea what causes it, but I'm pretty sure it's to do with FiveM and not the radar. 

If you're the server owner, you could try using the latest version from the `passenger-control` branch, which is the beta version of the radar. 

You could try moving your cache folder out of your FiveM client folder to test if it works then?

**Comment by WhackySnax** [comment]
I ended up getting it to work by re-installing my GTA 5 somehow. I was also wondering if there is any way you can make it so you're able to catch speed on a horizontal axis, instead of positioning your car at a certain degree to catch the same and opposite speeds. Example: your sitting perpendicular to the road and able to read speeds going in front of you going both directions.

**Comment by WolfKnight98** [comment]
Glad to hear it's sorted. 

In regards to your request, it is possible but the way it is designed is intentional, see here: https://github.com/WolfKnight98/wk_wars2x/pull/1


If you want to remove the limitation cone, do this:
Open cl_radar.lua and go to line 826, change it from:
`if ( hit and self:IsVehicleInTraffic( veh, relPos ) ) then`

to
`if ( hit ) then `
