### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by beauflexx** [WolfKnight98/wk_wars2x#12]
**Describe the bug**
Moved and Resized the HUD for the place reader, it disappeared. 

**To Reproduce**
Moved License plate reader, disappeared. Havent been able to reproduce, it doesnt show up anymore. Tried reinstalling. 
Tried the beta didnt help.
Wondering where the UI settings are saved?

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - FiveM version Updated
 - FiveM server version Up to date, 1.2
 - Radar version [e.g. 1.2.4]

**Additional context**

**Comment by WolfKnight98** [comment]
Whilst in-game, type /reset_radar_data in chat, then fully restart FiveM without opening the remote. Load the game and try again.
