### ISSUE TITLE
Radar Display Issue

### ISSUE THREAD

**Issue by diddleman1995** [WolfKnight98/wk_wars2x#13]
Describe the bug
Issue with display of the radar and license plate reader. Only happens when something else is opened as administrator on computer. Some programs: OBS/SLOBS, Voicemeeter (all versions)

To Reproduce
Start any application as administrator then open FiveM and try using the radar. When not done and only FiveM is started, remote, radar, and license plate reader works perfectly.

Expected behaviour
Even if other programs are opened as administrator, all functions should still work without issue. Not sure if it's just a fluke on my end, or if it's a known issue with a fix.

Screenshots
N/A at this time. At time of creating issue, I am on my mobile.

Desktop (please complete the following information):

FiveM version: Up to date as of 1/26/2021
FiveM server version: Up to date as of 1/26/2021
Radar version [e.g. 1.2.4]: Up to date (to my knowledge. Will double check when I get on again)
Additional context

**Comment by eramsorgr** [comment]
Can not reproduce. Running latest, Admin on OBS and Voicemeeter potato

**Comment by WolfKnight98** [comment]
I've never had this issue and I always have Discord open (as administrator) when I'm coding for/playing FiveM. I am also unable to reproduce your issue, the only thing I could think of is running FiveM as administrator?

**Comment by diddleman1995** [comment]
FiveM does not allow it to be ran as administrator. Sadly. I'll figure something out. Thank you

**Comment by oGhosti** [comment]
> 
> 
> Describe the bug
> Issue with display of the radar and license plate reader. Only happens when something else is opened as administrator on computer. Some programs: OBS/SLOBS, Voicemeeter (all versions)
> 
> To Reproduce
> Start any application as administrator then open FiveM and try using the radar. When not done and only FiveM is started, remote, radar, and license plate reader works perfectly.
> 
> Expected behaviour
> Even if other programs are opened as administrator, all functions should still work without issue. Not sure if it's just a fluke on my end, or if it's a known issue with a fix.
> 
> Screenshots
> If applicable, add screenshots to help explain your problem.
> N/A at this time. At time of creating issue, I am on my mobile.
> 
> Desktop (please complete the following information):
> 
> FiveM version: Up to date as of 1/26/2021
> FiveM server version: Up to date as of 1/26/2021
> Radar version [e.g. 1.2.4]: Up to date (to my knowledge. Will double check when I get on again)
> Additional context
> Add any other context about the problem here.

+1 to this. 
Been having issues on and off..

**Comment by SilverNick** [comment]
Same issue when you press toggle display it does not open radar

**Comment by WolfKnight98** [comment]
> 
> 
> > Describe the bug
> > Issue with display of the radar and license plate reader. Only happens when something else is opened as administrator on computer. Some programs: OBS/SLOBS, Voicemeeter (all versions)
> > To Reproduce
> > Start any application as administrator then open FiveM and try using the radar. When not done and only FiveM is started, remote, radar, and license plate reader works perfectly.
> > Expected behaviour
> > Even if other programs are opened as administrator, all functions should still work without issue. Not sure if it's just a fluke on my end, or if it's a known issue with a fix.
> > Screenshots
> > If applicable, add screenshots to help explain your problem.
> > N/A at this time. At time of creating issue, I am on my mobile.
> > Desktop (please complete the following information):
> > FiveM version: Up to date as of 1/26/2021
> > FiveM server version: Up to date as of 1/26/2021
> > Radar version [e.g. 1.2.4]: Up to date (to my knowledge. Will double check when I get on again)
> > Additional context
> > Add any other context about the problem here.
> 
> +1 to this.
> Been having issues on and off..
> Remote can open, help can open, plate reader can open (Not the actual PLATES part though), and UI Settings can open.
> 
> Radar itself can not be opened, nor can the plate locks.
> 
> Only things I'm aware of that are running as admin are FlawlessWidescreen, Medal.tv, & Clownfish Voice Changer. I've closed all of those to test, did not fix.

The issue you've described has been reported a number of times to me since I released the radar, sadly though I've got no idea what causes it, and it's never happened to me so I can't debug it from my end. The only things I can suggest are either try out every fix in the `FAQ and Troubleshooting` section on the forum post, or try the latest beta version from the `passenger-control` branch.

**Comment by tiger1974** [comment]
I'm having the same issue.  I did manage to capture this in nui devtools
![Screenshot_3](https://user-images.githubusercontent.com/1722833/107864627-5f7afc80-6e1b-11eb-8182-fcb2dfbf1f44.png)

**Comment by WolfKnight98** [comment]
> 
> 
> @WolfKnight98
> I'm having the same issue. I did manage to capture this in nui devtools
> ![Screenshot_3](https://user-images.githubusercontent.com/1722833/107864627-5f7afc80-6e1b-11eb-8182-fcb2dfbf1f44.png)

Bloody brilliant mate, first bit of useful help I've had! Looks like it might be caused by the included jQuery file, try this:

Open `radar.html` and scroll to the very bottom, look for `<script src="jquery-3.4.1.min.js"></script>` and change it to `<script src="nui://game/ui/jquery.js" type="text/javascript"></script>`

See if that does anything, let me know.

**Comment by tiger1974** [comment]
Sorry @WolfKnight98 I just saw this. I'll make that change and see what happens. I'll let you know either way.

**Comment by Dimmies** [comment]
I was having a similar issue, had the exact same errors in Chrome Devtools as well. Tracked it down to this chunk:

```
function sendData( name, data ) {
	$.post( "http://" + resourceName + "/" + name, JSON.stringify( data ), function( datab ) {
		if ( datab != "ok" ) {
			console.log( datab );
		}            
	} );
}
```

Seems like when I would log the `resourceName` var, it would return undefined. I replaced it with the script name `wk_wars2x` and it seemed to work just fine.

```
function sendData( name, data ) {
	console.log(resourceName, name)
	$.post( "http://wk_wars2x/" + name, JSON.stringify( data ), function( datab ) {
		if ( datab != "ok" ) {
			console.log( datab );
		}            
	} );
}
```

@WolfKnight98 This could be part of your solution :)

**Comment by WolfKnight98** [comment]
> 
> 
> I was having a similar issue, had the exact same errors in Chrome Devtools as well. Tracked it down to this chunk:
> 
> ```
> function sendData( name, data ) {
> 	$.post( "http://" + resourceName + "/" + name, JSON.stringify( data ), function( datab ) {
> 		if ( datab != "ok" ) {
> 			console.log( datab );
> 		}            
> 	} );
> }
> ```
> 
> Seems like when I would log the `resourceName` var, it would return undefined. I replaced it with the script name `wk_wars2x` and it seemed to work just fine.
> 
> ```
> function sendData( name, data ) {
> 	console.log(resourceName, name)
> 	$.post( "http://wk_wars2x/" + name, JSON.stringify( data ), function( datab ) {
> 		if ( datab != "ok" ) {
> 			console.log( datab );
> 		}            
> 	} );
> }
> ```
> 
> @WolfKnight98 This could be part of your solution :)

Funny you should mention that, I actually removed the dynamic resource naming on the `passenger-control` branch a while ago. I really need to finish that up so I can release it. Good find.

**Comment by WolfKnight98** [comment]
@diddleman1995 Can you confirm if the changes from https://github.com/WolfKnight98/wk_wars2x/commit/a0ef45c60d5044176f4a1e4ff2b66f8df8a34aed have fixed the issue for you?
