### ISSUE TITLE
How can i add addon vehicle to the script?

### ISSUE THREAD

**Issue by xXMrPotatoXx** [WolfKnight98/wk_wars2x#15]
Everything is working but i dont know how to add addon vehicle to the script. Is there any way i can add vehicle to the script?

**Comment by MichaelCoding25** [comment]
You need to designate that vehicle as an emergency vehicle

**Comment by WolfKnight98** [comment]
Like @MichaelCoding25 said, you need to set the vehicle class to `VC_EMERGENCY` in their vehicles.meta file. 

I am closing this issue as it is unrelated to the radar.
