### ISSUE TITLE
[SUGGESTION] Job check

### ISSUE THREAD

**Issue by Jaccosf** [WolfKnight98/wk_wars2x#17]
**What is your suggestion?**
Maybe you could add a check on the player job. Other emergency vehicles then police vehicles can use it too now.

**Comment by WolfKnight98** [comment]
The resource is standalone and will remain that way. I'll never add in framework job checks.

As for being able to open the radar in other types of emergency vehicles, refer back to your issue #9

**Comment by Jaccosf** [comment]
I didn't even know I already said that, I'm sorry for that. Thanks for the quick reaction.
