### ISSUE TITLE
[BUG] new five M update disables hot keys for wraith

### ISSUE THREAD

**Issue by Contra2828** [WolfKnight98/wk_wars2x#19]
**Describe the bug**
fivem keys for wraith disappeared after fivem update

**To Reproduce**
try to use wraith ARS after todays update

**Expected behaviour**
Would be able to access the radar / keybinds

**Screenshots**

**Desktop (please complete the following information):**
 - FiveM version
 - FiveM server version
 - Radar version [e.g. 1.0.0]

**Additional context**

**Comment by MichaelCoding25** [comment]
I am on the canary build of fivem (v1.0.0.4059) and the keybinds work fine for me, literally just tried it.

**Comment by Contra2828** [comment]
Going to try reinstalling it, the one i have came with sonoran, maybe that is the cause

**Comment by Contra2828** [comment]
After reinstall it works fine, you can close this ticket!

**Comment by WolfKnight98** [comment]
> 
> 
> Going to try reinstalling it, the one i have came with sonoran, maybe that is the cause

Just a heads up, I wouldn't use the version that comes with SonoranCAD. Always ensure you use the latest version from this GitHub repository's release section.
