### ISSUE TITLE
Radar is checking speeds of airplanes/helicopters/etc

### ISSUE THREAD

**Issue by shivm1221** [WolfKnight98/wk_wars2x#2]
Detailed in the following FiveM forum post; https://forum.cfx.re/t/release-wraith-ars-2x-police-radar-and-plate-reader-v1-1-1/1058277/148?u=sadps5m

**Comment by WolfKnight98** [comment]
Will crack on with fixing this tomorrow.

**Comment by WolfKnight98** [comment]
Should be fixed with version 1.1.2
