### ISSUE TITLE
[BUG] i can see my radar remote but when i hit toggle display the actual radar doesnt pop up 

### ISSUE THREAD

**Issue by Evan2211** [WolfKnight98/wk_wars2x#20]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - FiveM version
 - FiveM server version
 - Radar version [e.g. 1.0.0]

**Additional context**

**Comment by WolfKnight98** [comment]
You need to type `/reset_radar_data` in chat, then immediately restart your game.

**Comment by Little-Poney** [comment]
Hello,

when I press the F5 key or type /radar_remote or /radar no radar appears. 
I have no error message whatsoever in game or on my server console.

Your other "wraith_alpr" to "wk_wrs" versions work fine.

Could you help me please ?

FYI: i used also /reset_radar_data
