### ISSUE TITLE
[BUG] Can't use your radar

### ISSUE THREAD

**Issue by Little-Poney** [WolfKnight98/wk_wars2x#21]
**Describe the bug**
I can't use the radar

**To Reproduce**
when I press the F5 key or type / radar_remote or / radar no radar appears.

**Expected behaviour**
I would like to use the function 'radar'

**Screenshots**
https://ibb.co/PCfdGKK

**Desktop (please complete the following information):**
 - FiveM Last version
 - FiveM server Qbus Framework Last version
 - Radar version [e.g. 1.3.0]

**Additional context**
I have no error message whatsoever in game or on my server console.
FYI: i used also /reset_radar_data
When I stoped and restarted i have this message (Screenshot)

**Comment by WolfKnight98** [comment]
Try resetting your GTA V key bindings.

**Comment by philsjh** [comment]
+1 - getting an issue where pressing the keybind freezes the game as if something is open in front of it. Tried resetting radar data, clearing cache, and binding it to a different key but no joy. Latest version of both the plugin and fivem

**Comment by Little-Poney** [comment]
Hi, 
Sorry but after I reset my hotkey settings the script still doesn't work and I still have the message in my console.
And I tried to change the option in your config.lua. 
**For example:**

-- Remote control key
	remote_control = **"f5",**
to 
-- Remote control key
	remote_control = **"o",**

**Screenshots**
https://ibb.co/PCfdGKK

Thank you for you help.

**Comment by WolfKnight98** [comment]
> 
> 
> +1 - getting an issue where pressing the keybind freezes the game as if something is open in front of it. Tried resetting radar data, clearing cache, and binding it to a different key but no joy. Latest version of both the plugin and fivem

Have you tried downloading a new FiveM.exe into a folder on your desktop, and then tried running that and seeing if it works? You could also try taking your clientside cache folder out, and give that a go. 


> 
> 
> Hi,
> Sorry but after I reset my hotkey settings the script still doesn't work and I still have the message in my console.
> And I tried to change the option in your config.lua.
> **For example:**
> 
> -- Remote control key
> remote_control = **"f5",**
> to
> -- Remote control key
> remote_control = **"o",**
> 
> **Screenshots**
> https://ibb.co/PCfdGKK
> 
> Thank you for you help.

Changing the default keys in the configuration file only works for players who have never had their key binds generated. You'd need t change yours in the FiveM section of GTA's key bindings menu. 

Those messages in your console are normal.

**Comment by Little-Poney** [comment]
Hi,
thank you for your reply. but in fact I am using the latest version of FiveM and I have nothing (Radar option) in the FiveM section of the GTA hotkey menu.

**Comment by WolfKnight98** [comment]
> 
> 
> Hi,
> thank you for your reply. but in fact I am using the latest version of FiveM and I have nothing (Radar option) in the FiveM section of the GTA hotkey menu.

Just out of curiosity, are you using the radar version that comes with Sonoran CAD?

**Comment by Little-Poney** [comment]
hello, i only use your latest version. I deleted my cache on my server and on my client and also reinstalled the latest version of FiveM.

**Comment by WolfKnight98** [comment]
> 
> 
> hello, i only use your latest version. I deleted my cache on my server and on my client and also reinstalled the latest version of FiveM.

I'm a bit stumped then. Try this:

Open Windows Explorer and navigate to C:\Users\<username>\AppData\Roaming\CitizenFX and open the file named fivem.cfg with a program like Notepad++. Once open, delete all of the lines that start with rbind wk_wars2x, for example, all of mine are:

```
rbind wk_wars2x KEYBOARD L "radar_key_lock"
rbind wk_wars2x KEYBOARD NUMPAD5 "radar_bk_ant"
rbind wk_wars2x KEYBOARD NUMPAD6 "radar_bk_cam"
rbind wk_wars2x KEYBOARD NUMPAD8 "radar_fr_ant"
rbind wk_wars2x KEYBOARD NUMPAD9 "radar_fr_cam"
rbind wk_wars2x KEYBOARD F5 "radar_remote"
```

**Comment by philsjh** [comment]
Yeah, I've tried this, still doesn't work - deleted cache, rebinded keys, the whole heap. Nothing :(

**Comment by philsjh** [comment]
Also just tried a full delete and reinstall - still nothing

**Comment by philsjh** [comment]
I opened the console:

![image](https://user-images.githubusercontent.com/1872162/125180412-b41b7b80-e1f1-11eb-8a72-67d8b9e2d264.png)

Not sure if this helps

**Comment by WolfKnight98** [comment]
> 
> 
> I opened the console:
> 
> ![image](https://user-images.githubusercontent.com/1872162/125180412-b41b7b80-e1f1-11eb-8a72-67d8b9e2d264.png)
> 
> Not sure if this helps

What is the name of the resource in your resource folder?
