### ISSUE TITLE
Problems on QBUS opening controller

### ISSUE THREAD

**Issue by Shaine415** [WolfKnight98/wk_wars2x#24]
Not quite sure how to fix this. Is live console shows no errors and all up to date but when load into FIveM i get 4 messages (screenshot provided) and i cant find information anywhere to resolve this. Thankyou
![error 1](https://user-images.githubusercontent.com/93155991/138752156-488bd0d1-fd06-4ef6-a924-c556ec6b7753.png)

**Comment by WolfKnight98** [comment]
Those messages are normal.

**Comment by Shaine415** [comment]
> Those messages are normal.

Oh ok. wasnt sure because pressing F5 dont bring up my controller so thought it was not working

**Comment by Shaine415** [comment]
Ignore me. F4 brought controller up
