### ISSUE TITLE
[BUG] Good evening or afternoon or morning, I got a problem from some people that radar is not working. The remoter is showing up, but the radar and plater reader is not working, I don't know if anyone else have this problem, But when you have time can you checking it or we doing a VC to get some help on it? Thank you very much. I will update you if we got it some how fixed.  

### ISSUE THREAD

**Issue by GhostTiger11** [WolfKnight98/wk_wars2x#26]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - FiveM version
 - FiveM server version
 - Radar version [e.g. 1.0.0]

**Additional context**

**Comment by alex-leona** [comment]
I was having the same problem. I looked back under the solved cases and I found this problem with the fix. You want to do "/reset_radar_data" in the text chat then reset your game right away.

**Comment by GhostTiger11** [comment]
> I was having the same problem. I looked back under the solved cases and I found this problem with the fix. You want to do "/reset_radar_data" in the text chat then reset your game right away.

Ok, I will try it, thank you very much for you help.
