### ISSUE TITLE
[BUG] Radar can be opened in ambulance

### ISSUE THREAD

**Issue by Deliuxas** [WolfKnight98/wk_wars2x#27]
**Describe the bug**
Radar can be opened in ambulance car. Even if you don't have police job.

**To Reproduce**
Sit down to ambulance car and try to open radar.

**Comment by MichaelCoding25** [comment]
That is intended behavior, the radar is usable in any emergency vehicle, if you would like to restrict it to only certain vehicles for your server you're welcome to do so yourself.

**Comment by Pyth3rEx** [comment]
added in #59
