### ISSUE TITLE
[BUG] Radar not working issue in cl_radar.lua line 162

### ISSUE THREAD

**Issue by tencreator** [WolfKnight98/wk_wars2x#28]
**Describe the bug**
I am unable to open radar after a fresh install

**Screenshots**
![image](https://user-images.githubusercontent.com/45293208/152641966-8bc10e6a-9c05-43a3-bd0d-64d6e8dafe63.png)

**Desktop (please complete the following information):**
 - FiveM version : 2545 
 - FiveM server version : 5298/ZAP
 - Radar version : 1.3.1

**Additional context**
I have tried debugging but without any success

**Comment by samuelcardillo** [comment]
I am having the exact same issue. No idea yet on how to fix this?

**Comment by TrueSunnyD** [comment]
That is showing that you guys messed up something in the config.

**Comment by Cata-a1138** [comment]
I have the same problem. I hope it can be solved as soon as possible. Thank you

**Comment by Cata-a1138** [comment]
This problem has now been solved.

**Comment by Cata-a1138** [comment]
This problem has now been solved
Sorry, my English is not very good, so I just copy the author's words
"Open the zip file and place the wk_wars2x folder into your server's resource folder"
Like me,
![image](https://user-images.githubusercontent.com/108532800/188321057-dc598503-42a8-4414-a6cf-288e49261b4a.png)
