### ISSUE TITLE
[BUG] Causes client crash

### ISSUE THREAD

**Issue by gr4v86** [WolfKnight98/wk_wars2x#5]
When the resource is running and using a helicopter when you left click the client crashes. 

When you stop the resource you no longer crash when left clicking.

**Comment by WolfKnight98** [comment]
Copied directly from the forum post:

**My game crashes when I try to use mouse control in a land/air vehicle?**
- There is currently a bug with FiveM that causes the game to crash if a key bind set with the `RegisterKeyMapping` function is the same as a vehicle movement key. There is a temporary solution though, go into your key bindings menu and change the radar’s keys to anything that isn’t the same as a vehicle’s movement key.

**Comment by gr4v86** [comment]
thanks for the reply
