### ISSUE TITLE
radar toggle display not working 

### ISSUE THREAD

**Issue by jsheehan51342** [WolfKnight98/wk_wars2x#7]
so all my keys work fine but when I hit F5 to open the rader it opens but the menu and toggle display button for plate reader and radar don't do anything

**Comment by WolfKnight98** [comment]
Are you the owner of the server? That sounds like the usual issue of the resource being renamed.

**Comment by jsheehan51342** [comment]
I am not the owner the owner can not figure out the issue It works for everyone else in the server but not me

**Comment by WolfKnight98** [comment]
Huh, okay. Are there any errors in the F8 console?

**Comment by jsheehan51342** [comment]
all is says is saved ui setting and data loaded no errors

**Comment by WolfKnight98** [comment]
Try typing `/reset_radar_data` in chat, sometimes the radar can go off screen, not sure why.

**Comment by jsheehan51342** [comment]
that did not work either it did reset it but my toggle displays and menu still do not work

**Comment by WolfKnight98** [comment]
Does anyone else on the server have the same problem?

**Comment by jsheehan51342** [comment]
no as of right now its just me

**Comment by WolfKnight98** [comment]
I'll be honest with you mate, I'm a bit stumped. Would you be willing to try a fresh second install of FiveM just for testing?

**Comment by jsheehan51342** [comment]
I completely uninstalled five m restarted my computer and the reinstalled it already it was working fine like a week ago

**Comment by WolfKnight98** [comment]
Can you ask the server owner if he has renamed the resource?

**Comment by jsheehan51342** [comment]
yes I will ask

**Comment by jsheehan51342** [comment]
so I talked to the owner and he has not changed a thing with it

**Comment by WolfKnight98** [comment]
Okay... odd. 

If you click toggle display, and then click say the front XMIT button, do you hear a beep?

**Comment by jsheehan51342** [comment]
okay so for some reason it has started working again im not sure why I dident do anything different but it does work thank you so much

**Comment by dlyth** [comment]
im having the same issues
was working perfectly then now its not working all together
