### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by skavich** [WolfKnight98/wk_wars2x#8]
**Describe the bug**
there is no way to set the top speed anymore so radar goes off when someone breaks the limit

**Comment by WolfKnight98** [comment]
This has always been a feature, it has to be enabled first in `config.lua`.

**Comment by skavich** [comment]
ok my bad then, im just an officer on a server, it just seemed to dissapear after an update, i will speak to the devs on the sever. thank you for getting back to me.
