### ISSUE TITLE
Emergencies

### ISSUE THREAD

**Issue by Jaccosf** [WolfKnight98/wk_wars2x#9]
**Describe the bug**
The radar doesn't only work for police vehicles, but also for ambulance etc etc

**Expected behaviour**
I hope you guys have a solution for me for that or that you just edit it.

**Comment by WolfKnight98** [comment]
It's not a bug, it's intentional. Adding an additional layer to the vehicle check that also checks the vehicle model against a whitelist is something I've considered, but in the end seemed like a waste of performance. I may look at it again at some point.
